Opetushallitus/oti

resources/oti/public/css/main.css
resources/oti/queries.sql
src/clj/oti/boundary/db_access.clj
src/clj/oti/endpoint/virkailija.clj
src/cljc/oti/spec.cljc
src/cljs/oti/ui/views/exam_sessions.cljs
src/less/_exam-sessions.less

First attempt on using translations in the pipeline

Hotfix ui knows about translations

---

dev/resources/dev.edn
dev/src/dev.clj
resources/oti/system.edn
src/clj/oti/endpoint/virkailija.clj
src/clj/oti/util/logging/exception.clj

Korjaa poikkeuksien lokituksen.

OTI-84_exception_logging

---

resources/oti/oti_url.properties
src/clj/oti/component/paytrail_payment.clj

- Korjaa suomifi login
- Korjaa paytrail integraatio

OTI-96 suomifi login

---

dev/resources/logback.xml
oph-configuration/logback.xml.template
project.clj
src/clj/oti/endpoint/auth.clj
src/clj/oti/endpoint/payment.clj
src/clj/oti/endpoint/virkailija.clj
src/clj/oti/service/accreditation.clj
src/clj/oti/service/diploma.clj
src/clj/oti/service/payment.clj
src/clj/oti/service/registration.clj
src/clj/oti/service/scoring.clj
src/clj/oti/util/logging/audit.clj
src/clj/oti/util/logging/core.clj
test/oti/endpoint/auth_test.clj

Upgrade to auditlogger 8.2.0-SNAPSHOT

---

resources/oti/queries.sql

Registration was not possible if previous try was today.
OTI-105

Fix registration for retry

---

resources/oti/migrations/040-new-modules.up.sql
resources/oti/migrations/041-all-executed-as-whole.up.sql
src/cljc/oti/exam_rules.cljc

New module names

---

resources/oti/queries.sql
src/clj/oti/boundary/db_access.clj
src/cljs/oti/ui/registration/views/registration.cljs

Add essay accreditation to registration

---

resources/oti/public/css/main.css
src/cljs/oti/ui/registration/views/registration.cljs
src/less/_forms.less

Add empty exam session as default in registration

---

src/clj/oti/service/user_data.clj

Fix address mapping

---

resources/oti/queries.sql
src/clj/oti/boundary/db_access.clj
src/clj/oti/service/payment.clj

Fix registration email

---

resources/oti/queries.sql
src/clj/oti/boundary/db_access.clj
src/clj/oti/endpoint/virkailija.clj
src/clj/oti/service/accreditation.clj
src/clj/oti/util/logging/audit.clj
src/cljs/oti/ui/participants/handlers.cljs
src/cljs/oti/ui/participants/views/details.cljs

Add accreditation delete

---

resources/oti/migrations/042-session-participant-limit-trigger-fix.up.sql
resources/oti/queries.sql
src/clj/oti/boundary/db_access.clj
src/clj/oti/component/scheduler.clj
src/clj/oti/service/payment.clj

Add scheduled task to cancel obsolete payments

---

src/clj/oti/service/user_data.clj
src/clj/oti/util/coercion.clj
src/cljs/oti/ui/exam_sessions/exam_session.cljs
src/cljs/oti/ui/exam_sessions/utils.cljs
src/cljs/oti/ui/participants/views/details.cljs

Fix session date timezone bug

---

project.clj
resources/oti/public/css/main.css
resources/oti/queries.sql
src/clj/oti/boundary/db_access.clj
src/clj/oti/endpoint/virkailija.clj
src/clj/oti/service/payment.clj
src/clj/oti/util/csv.clj
src/cljs/oti/ui/reporting/views.cljs
src/cljs/oti/ui/routes.cljs
src/cljs/oti/ui/views/common.cljs
src/cljs/oti/ui/views/virkailija_main.cljs
src/less/_reporting.less
src/less/main.less

Add payment report

---

src/cljs/oti/ui/handlers.cljs
src/cljs/oti/ui/registration/views/registration.cljs
src/cljs/oti/ui/views/common.cljs

Add confirmation modal to registration

---

src/clj/oti/endpoint/virkailija.clj
src/cljs/oti/ui/reporting/views.cljs

Fix payment report end date

---

src/cljc/oti/spec.cljc

Fix iso date validation

---

resources/oti/queries.sql
src/clj/oti/boundary/db_access.clj
src/clj/oti/endpoint/virkailija.clj
src/cljs/oti/ui/participants/handlers.cljs
src/cljs/oti/ui/participants/views/details.cljs

Includes quite a lot of formatting changes, do disable whitespace comparison

OTI-169: editable email address

---

src/cljc/oti/spec.cljc
src/cljs/oti/ui/participants/views/search.cljs

* Adjust form validation to work with upgraded spec.alpha

OTI-174: Fix printing

---

src/cljc/oti/spec.cljc
src/cljs/oti/ui/registration/views/registration.cljs

* Fix regression introduced by spec.alpha update

OTI-175: Restore ability to enroll only to some retry modules
